package view;

import controller.Controller;

/**
 *
 * @author jcgd
 */
public class View extends javax.swing.JFrame {
    Controller cont;
    /**
     * Creates new form View
     * @param c controller
     */
    public View(Controller c) {
        cont = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldOriginal = new javax.swing.JTextField();
        jTextFieldCifrado = new javax.swing.JTextField();
        jSliderClave = new javax.swing.JSlider();
        jLabelClave = new javax.swing.JLabel();
        jLabelEnigma = new javax.swing.JLabel();
        jLabelADP = new javax.swing.JLabel();
        jLabelOriginal = new javax.swing.JLabel();
        jLabelDescifrado = new javax.swing.JLabel();
        jRadioButtonCifrar = new javax.swing.JRadioButton();
        jRadioButtonDescifrar = new javax.swing.JRadioButton();
        jTextFieldClave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-nigma");
        setResizable(false);

        jTextFieldOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldOriginalKeyReleased(evt);
            }
        });

        jTextFieldCifrado.setEditable(false);
        jTextFieldCifrado.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextFieldCifrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCifradoActionPerformed(evt);
            }
        });

        jSliderClave.setMaximum(26);
        jSliderClave.setMinimum(1);
        jSliderClave.setPaintLabels(true);
        jSliderClave.setPaintTicks(true);
        jSliderClave.setToolTipText("");
        jSliderClave.setValue(5);
        jSliderClave.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderClaveStateChanged(evt);
            }
        });

        jLabelClave.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jLabelClave.setText("Clave");

        jLabelEnigma.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabelEnigma.setText("E-nigma");

        jLabelADP.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jLabelADP.setText("Aprendizaje y desarrollo de la personalidad");

        jLabelOriginal.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jLabelOriginal.setText("Texto original");

        jLabelDescifrado.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jLabelDescifrado.setText("Texto (des)cifrado");

        buttonGroup1.add(jRadioButtonCifrar);
        jRadioButtonCifrar.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jRadioButtonCifrar.setSelected(true);
        jRadioButtonCifrar.setText("Cifrar");
        jRadioButtonCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCifrarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonDescifrar);
        jRadioButtonDescifrar.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jRadioButtonDescifrar.setText("Descifrar");
        jRadioButtonDescifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDescifrarActionPerformed(evt);
            }
        });

        jTextFieldClave.setEditable(false);
        jTextFieldClave.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        jTextFieldClave.setText("5");
        jTextFieldClave.setCaretColor(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelClave)
                                    .addComponent(jLabelEnigma, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSliderClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldClave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelADP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelDescifrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCifrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelEnigma, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCifrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClave, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSliderClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonDescifrar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOriginal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCifrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescifrado))
                .addGap(30, 30, 30)
                .addComponent(jLabelADP)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderClaveStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderClaveStateChanged
        updateView();
    }//GEN-LAST:event_jSliderClaveStateChanged

    private void jRadioButtonCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCifrarActionPerformed
        updateView();
    }//GEN-LAST:event_jRadioButtonCifrarActionPerformed

    private void jRadioButtonDescifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDescifrarActionPerformed
        updateView();
    }//GEN-LAST:event_jRadioButtonDescifrarActionPerformed

    private void jTextFieldOriginalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOriginalKeyReleased
        updateView();
    }//GEN-LAST:event_jTextFieldOriginalKeyReleased

    private void jTextFieldCifradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCifradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCifradoActionPerformed

    private void updateView(){
        int key = jSliderClave.getValue();
        boolean encrypt = jRadioButtonCifrar.isSelected();
        String originalText = jTextFieldOriginal.getText();
        jTextFieldClave.setText(Integer.toString(key));
        if (encrypt && originalText != null && !originalText.equals("")){
            jTextFieldCifrado.setText(cont.cypher(originalText, key));
        }else{
            if (!encrypt && originalText != null && !originalText.equals("")){
               jTextFieldCifrado.setText(cont.cypher(originalText, key*(-1))); 
            }
        }
    }
    public void run() {
        Controller c = new Controller();
        new View(c).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelADP;
    private javax.swing.JLabel jLabelClave;
    private javax.swing.JLabel jLabelDescifrado;
    private javax.swing.JLabel jLabelEnigma;
    private javax.swing.JLabel jLabelOriginal;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonCifrar;
    private javax.swing.JRadioButton jRadioButtonDescifrar;
    private javax.swing.JSlider jSliderClave;
    private javax.swing.JTextField jTextFieldCifrado;
    private javax.swing.JTextField jTextFieldClave;
    private javax.swing.JTextField jTextFieldOriginal;
    // End of variables declaration//GEN-END:variables
}
